version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
    volumes:
      - ./src/backend:/app
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - math-solver-network

  # Simple HTTP server for Flutter web build
  # frontend:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./src/frontend/build/web:/usr/share/nginx/html
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #   networks:
  #     - math-solver-network

  # Firebase Emulator (Optional for development)
  # firebase-emulator:
  #   image: node:18-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./firebase:/app
  #   command: >
  #     sh -c "npm install -g firebase-tools && \
  #            firebase emulators:start --project demo-project --only auth,functions,firestore,hosting"
  #   ports:
  #     - "4000:4000"   # Emulator UI
  #     - "9099:9099"   # Auth
  #     - "5001:5001"   # Functions
  #     - "8081:8081"   # Firestore (match firebase.json if changed)
  #     - "8085:8085"   # Hosting
  #   networks:
  #     - math-solver-network

networks:
  math-solver-network:
    driver: bridge

volumes:
  uploads:
